FROM ft-rails:on-build

EXPOSE 3000

#  s - server
# -b - binding
# -p - port
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# Build and run from ex02 folder.
# docker build -t ex02 .
# docker run --rm -dit -p 3000:3000 --name ex02 ex02
